name: check

on: [push]
jobs:
 build-and-deploy:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout 🛎️
     uses: actions/checkout@v2.3.1
     with:
      persist-credentials: false

   - name: Install
     run: |
      sudo apt install git -y

   - name: Install
     run: |
      npm i

   - name: Start 
     run: |
      npm run start