name: ipfs
on: [push]
jobs:
 build-and-deploy:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout 🛎️
     uses: actions/checkout@v2.3.1
     with:
      persist-credentials: false

   - name: Install
     run: |
      sudo apt install git -y

   - name: Build
     run: |
      npm i
      npm run start

   - name: View 
     run: |
      cat results.txt
